- name: cron security
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - stat:
        path: "{{ sysconfdir }}/anacrontab"
      register: anacrontab_result
    
    - stat:
        path: "{{ sysconfdir }}/crontab"
      register: crontab_result
    
    - name: "[error] Anacrontab is owned by root"
      file:
        path: "{{ sysconfdir }}/anacrontab"
        owner: 0
      when:
        - anacrontab_result.stat.exists == true

    - name: "[error] Anacrontab has correct file mask"
      file:
        path: "{{ sysconfdir }}/anacrontab"
        mode: "og-rwx"
      when:
        - anacrontab_result.stat.exists == true

    - name: "[error] crontabs are owned by root"
      file:
        path: "{{ item }}"
        owner: 0
      with_fileglob:
        - "{{ sysconfdir }}/cron*"
      when:
        - crontab_result.stat.exists == true
      
    - name: "[error] crontabs have correct file mask"
      file:
        path: "{{ item }}"
        mode: "og-rwx"
      with_fileglob:
        - "{{ sysconfdir }}/cron*"
      when:
        - crontab_result.stat.exists == true