- name: /etc security
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: "[error] /etc exists as a dir"
      file:
        path: "{{ sysconfdir }}"
        state: directory
    
    - name: "[error] Files in /etc are owned by root"
      file:
        path: "{{ sysconfdir }}/{{ item.path }}"
        owner: 0
      with_filetree:
        - "{{ sysconfdir }}"
      when:
        - item.state == "file"

    - name: "[error] Files in /etc are not writable by user"
      file:
        path: "{{ sysconfdir }}/{{ item.path }}"
        mode: "o-wx"
      with_filetree:
        - "{{ sysconfdir }}"
      when:
        - item.state == "file"