- name: modprobe security
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - stat:
        path: "{{ sysconfdir }}/modprobe.d/blacklist.conf"
      register: modprobe_result

    - name: "[error] Blacklist USB storage"
      lineinfile: 
        dest: "{{ sysconfdir }}/modprobe.d/blacklist.conf"
        regexp: '^blacklist'
        line: 'blacklist usb_storage'
      when:
        - modprobe_result.stat.exists == true