- name: sysconf security
  gather_facts: false
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "[error] Disable IPv4 forwarding"
      sysctl:
        name: "net.ipv4.ip_forward"
        value: 0
        sysctl_file: "{{ sysconfdir }}/sysctl.conf"

    - name: "[error] Disable the Send Packet Redirects 1/2"
      sysctl:
        name: "net.ipv4.conf.all.send_redirects"
        value: 0
        sysctl_file: "{{ sysconfdir }}/sysctl.conf"

    - name: "[error] Disable the Send Packet Redirects 2/2"
      sysctl:
        name: "net.ipv4.conf.default.send_redirects"
        value: 0
        sysctl_file: "{{ sysconfdir }}/sysctl.conf"
    
    - name: "[error] Disable ICMP Redirect Acceptance 1/2"
      sysctl:
        name: "net.ipv4.conf.all.accept_redirects"
        value: 0
        sysctl_file: "{{ sysconfdir }}/sysctl.conf"

    - name: "[error] Disable ICMP Redirect Acceptance 2/2"
      sysctl:
        name: "net.ipv4.conf.default.accept_redirects"
        value: 0
        sysctl_file: "{{ sysconfdir }}/sysctl.conf"

    - name: "[error] Enable Bad Error Message Protection"
      sysctl:
        name: "net.ipv4.icmp_ignore_bogus_error_responses"
        value: 1
        sysctl_file: "{{ sysconfdir }}/sysctl.conf"
